import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StoreProvider from "./StoreProvider";
import { Toaster } from "sonner";
import Header from "@/components/ui/Header";
import Navbar from "@/components/ui/Navbar";
import Footer from "@/components/ui/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <StoreProvider>
          <div className="relative">
            <Toaster />
            <header>
              <Header />
            </header>
            <nav className="sticky top-0 z-10">
              <Navbar />
            </nav>
            {children}
            <footer>
              <Footer />
            </footer>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
