import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StoreProvider from "./StoreProvider";
import { Toaster } from "sonner";
import Header from "@/components/ui/Header";
import Navbar from "@/components/ui/Navbar";
import Footer from "@/components/ui/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className} suppressHydrationWarning={true}>
          <Toaster />
          <header style={{ backgroundColor: "lightblue", padding: "1 rem" }}>
            <Header />
          </header>
          <nav style={{ backgroundColor: "lightgreen", padding: "1 rem" }}>
            <Navbar />
          </nav>
          {children}
          <footer style={{ backgroundColor: "lightgray", padding: "1 rem" }}>
            <Footer />
          </footer>
        </body>
      </html>
    </StoreProvider>
  );
}
